/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author oto_z
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.lbl_Acepto.setVisible(false);
        this.lbl_error.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_paciente = new javax.swing.JButton();
        btn_GrafEnf = new javax.swing.JButton();
        lay_Workbench = new javax.swing.JLayeredPane();
        pnl_Paciente = new javax.swing.JPanel();
        txt_Nombre = new javax.swing.JTextField();
        txt_Cedula = new javax.swing.JTextField();
        txt_fechNac = new javax.swing.JTextField();
        txt_Residencia = new javax.swing.JTextField();
        cbx_Enfermedades = new javax.swing.JComboBox<>();
        btn_AgregarEnf = new javax.swing.JButton();
        cbx_Med = new javax.swing.JComboBox<>();
        btn_AgregarMed = new javax.swing.JButton();
        lbl_Acepto = new javax.swing.JLabel();
        lbl_error = new javax.swing.JLabel();
        btn_Conf = new javax.swing.JButton();
        btn_Borrar = new javax.swing.JButton();
        btn_GrafPac = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        btn_GrafGeo = new javax.swing.JButton();
        lbl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_paciente.setBackground(new java.awt.Color(0, 0, 0));
        btn_paciente.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btn_paciente.setForeground(new java.awt.Color(255, 255, 255));
        btn_paciente.setText("Paciente");
        btn_paciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btn_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 30));

        btn_GrafEnf.setBackground(new java.awt.Color(0, 0, 0));
        btn_GrafEnf.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btn_GrafEnf.setForeground(new java.awt.Color(255, 255, 255));
        btn_GrafEnf.setText("Graficar Enfermedad");
        btn_GrafEnf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btn_GrafEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, 30));

        lay_Workbench.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnl_Paciente.setOpaque(false);
        pnl_Paciente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Nombre.setBackground(new java.awt.Color(0, 0, 0));
        txt_Nombre.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txt_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_Nombre.setText("Nombre");
        txt_Nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_NombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_NombreFocusLost(evt);
            }
        });
        pnl_Paciente.add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 290, -1));

        txt_Cedula.setBackground(new java.awt.Color(0, 0, 0));
        txt_Cedula.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txt_Cedula.setForeground(new java.awt.Color(255, 255, 255));
        txt_Cedula.setText("Cedula: ");
        txt_Cedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_CedulaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_CedulaFocusLost(evt);
            }
        });
        pnl_Paciente.add(txt_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 290, -1));

        txt_fechNac.setBackground(new java.awt.Color(0, 0, 0));
        txt_fechNac.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txt_fechNac.setForeground(new java.awt.Color(255, 255, 255));
        txt_fechNac.setText("Fecha Nacimiento: ");
        txt_fechNac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_fechNacFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_fechNacFocusLost(evt);
            }
        });
        txt_fechNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechNacActionPerformed(evt);
            }
        });
        pnl_Paciente.add(txt_fechNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 290, -1));

        txt_Residencia.setBackground(new java.awt.Color(0, 0, 0));
        txt_Residencia.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txt_Residencia.setForeground(new java.awt.Color(255, 255, 255));
        txt_Residencia.setText("Residencia: ");
        txt_Residencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_ResidenciaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_ResidenciaFocusLost(evt);
            }
        });
        pnl_Paciente.add(txt_Residencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 290, -1));

        cbx_Enfermedades.setBackground(new java.awt.Color(0, 0, 0));
        cbx_Enfermedades.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        cbx_Enfermedades.setForeground(new java.awt.Color(255, 255, 255));
        cbx_Enfermedades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enfermedades" }));
        pnl_Paciente.add(cbx_Enfermedades, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 290, -1));

        btn_AgregarEnf.setBackground(new java.awt.Color(0, 0, 0));
        btn_AgregarEnf.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_AgregarEnf.setForeground(new java.awt.Color(255, 255, 255));
        btn_AgregarEnf.setText("Agregar");
        pnl_Paciente.add(btn_AgregarEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 130, -1));

        cbx_Med.setBackground(new java.awt.Color(0, 0, 0));
        cbx_Med.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        cbx_Med.setForeground(new java.awt.Color(255, 255, 255));
        cbx_Med.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tratamiento" }));
        pnl_Paciente.add(cbx_Med, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 290, -1));

        btn_AgregarMed.setBackground(new java.awt.Color(0, 0, 0));
        btn_AgregarMed.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_AgregarMed.setForeground(new java.awt.Color(255, 255, 255));
        btn_AgregarMed.setText("Agregar");
        pnl_Paciente.add(btn_AgregarMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 130, -1));

        lbl_Acepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Acepto.jpg"))); // NOI18N
        pnl_Paciente.add(lbl_Acepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        lbl_error.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Error.png"))); // NOI18N
        pnl_Paciente.add(lbl_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, 300));

        btn_Conf.setBackground(new java.awt.Color(0, 0, 0));
        btn_Conf.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_Conf.setForeground(new java.awt.Color(255, 255, 255));
        btn_Conf.setText("Confirmar");
        btn_Conf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ConfMouseClicked(evt);
            }
        });
        pnl_Paciente.add(btn_Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 290, -1));

        btn_Borrar.setBackground(new java.awt.Color(0, 0, 0));
        btn_Borrar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_Borrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Borrar.setText("Borrar");
        btn_Borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BorrarMouseClicked(evt);
            }
        });
        pnl_Paciente.add(btn_Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 290, -1));

        lay_Workbench.setLayer(pnl_Paciente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lay_WorkbenchLayout = new javax.swing.GroupLayout(lay_Workbench);
        lay_Workbench.setLayout(lay_WorkbenchLayout);
        lay_WorkbenchLayout.setHorizontalGroup(
            lay_WorkbenchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lay_WorkbenchLayout.createSequentialGroup()
                .addComponent(pnl_Paciente, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                .addContainerGap())
        );
        lay_WorkbenchLayout.setVerticalGroup(
            lay_WorkbenchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Paciente, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );

        getContentPane().add(lay_Workbench, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 850, 620));

        btn_GrafPac.setBackground(new java.awt.Color(0, 0, 0));
        btn_GrafPac.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btn_GrafPac.setForeground(new java.awt.Color(255, 255, 255));
        btn_GrafPac.setText("Graficar Paciente");
        btn_GrafPac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btn_GrafPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 30));

        btn_Salir.setBackground(new java.awt.Color(0, 0, 0));
        btn_Salir.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btn_Salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 170, 30));

        btn_GrafGeo.setBackground(new java.awt.Color(0, 0, 0));
        btn_GrafGeo.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btn_GrafGeo.setForeground(new java.awt.Color(255, 255, 255));
        btn_GrafGeo.setText("Graficar Geografia");
        btn_GrafGeo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btn_GrafGeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, 30));

        lbl_Fondo.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(lbl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void txt_NombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NombreFocusGained
        txt_Nombre.setText("");
    }//GEN-LAST:event_txt_NombreFocusGained

    private void txt_NombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NombreFocusLost
        if("".equals(txt_Nombre.getText()) || " ".equals(txt_Nombre.getText())){
            txt_Nombre.setText("Nombre: ");
        }
    }//GEN-LAST:event_txt_NombreFocusLost

    private void txt_CedulaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CedulaFocusGained
        txt_Cedula.setText("");
    }//GEN-LAST:event_txt_CedulaFocusGained

    private void txt_CedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CedulaFocusLost
        if("".equals(txt_Cedula.getText()) || " ".equals(txt_Cedula.getText())){
            txt_Cedula.setText("Cedula: ");
        }
    }//GEN-LAST:event_txt_CedulaFocusLost

    private void txt_fechNacFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_fechNacFocusGained
        txt_fechNac.setText("");
    }//GEN-LAST:event_txt_fechNacFocusGained

    private void txt_fechNacFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_fechNacFocusLost
        if("".equals(txt_fechNac.getText()) || " ".equals(txt_fechNac.getText())){
            txt_fechNac.setText("Fecha Nacimiento: ");
        }
    }//GEN-LAST:event_txt_fechNacFocusLost

    private void txt_fechNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fechNacActionPerformed

    private void txt_ResidenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ResidenciaFocusGained
        txt_Residencia.setText("");
    }//GEN-LAST:event_txt_ResidenciaFocusGained

    private void txt_ResidenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ResidenciaFocusLost
        if("".equals(txt_Residencia.getText()) || " ".equals(txt_Residencia.getText())){
            txt_Residencia.setText("Fecha Nacimiento: ");
        }
    }//GEN-LAST:event_txt_ResidenciaFocusLost

    private void btn_BorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BorrarMouseClicked
        txt_Cedula.setText("Cedula: ");
        txt_Nombre.setText("Nombre: ");
        txt_Residencia.setText("Residencia: ");
        txt_fechNac.setText("Fecha Nacimiento: ");
        cbx_Enfermedades.setSelectedIndex(0);
        cbx_Med.setSelectedIndex(0);
        this.lbl_Acepto.setVisible(false);
        this.lbl_error.setVisible(false);
    }//GEN-LAST:event_btn_BorrarMouseClicked

    private void btn_ConfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ConfMouseClicked
        try {
            this.lbl_Acepto.setVisible(true);
        }
        catch (Exception e) {
            this.lbl_error.setVisible(true);
        }
    }//GEN-LAST:event_btn_ConfMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AgregarEnf;
    private javax.swing.JButton btn_AgregarMed;
    private javax.swing.JButton btn_Borrar;
    private javax.swing.JButton btn_Conf;
    private javax.swing.JButton btn_GrafEnf;
    private javax.swing.JButton btn_GrafGeo;
    private javax.swing.JButton btn_GrafPac;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JButton btn_paciente;
    private javax.swing.JComboBox<String> cbx_Enfermedades;
    private javax.swing.JComboBox<String> cbx_Med;
    private javax.swing.JLayeredPane lay_Workbench;
    private javax.swing.JLabel lbl_Acepto;
    private javax.swing.JLabel lbl_Fondo;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JPanel pnl_Paciente;
    private javax.swing.JTextField txt_Cedula;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Residencia;
    private javax.swing.JTextField txt_fechNac;
    // End of variables declaration//GEN-END:variables
}
