/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author oto_z
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_agregarPac = new javax.swing.JButton();
        btn_agregarEnf = new javax.swing.JButton();
        btn_agregarTrat = new javax.swing.JButton();
        lbl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_agregarPac.setBackground(new java.awt.Color(0, 0, 0));
        btn_agregarPac.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btn_agregarPac.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregarPac.setText("Agregar Paciente");
        btn_agregarPac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btn_agregarPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 30));

        btn_agregarEnf.setBackground(new java.awt.Color(0, 0, 0));
        btn_agregarEnf.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btn_agregarEnf.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregarEnf.setText("Agregar Enfermedad");
        btn_agregarEnf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btn_agregarEnf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, 30));

        btn_agregarTrat.setBackground(new java.awt.Color(0, 0, 0));
        btn_agregarTrat.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btn_agregarTrat.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregarTrat.setText("Agregar Tratamiento");
        btn_agregarTrat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btn_agregarTrat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 30));

        lbl_Fondo.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(lbl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarEnf;
    private javax.swing.JButton btn_agregarPac;
    private javax.swing.JButton btn_agregarTrat;
    private javax.swing.JLabel lbl_Fondo;
    // End of variables declaration//GEN-END:variables
}
